name: "Curse locale"
description: "addons localization auto scan/import/export action"
author: "Dencer"
inputs:
  curse-wow-token:
    description: "curse token"
    required: true
runs:
  using: "node20"
  main: "index.js"
branding:
  color: "blue"
  icon: "play"
